<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5vi3ZyN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5vi3ZyN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5vi3ZyN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5vi3ZyN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5vi3ZyN\App_KernelDevDebugContainer([
    'container.build_hash' => '5vi3ZyN',
    'container.build_id' => '2eb993ff',
    'container.build_time' => 1619701906,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5vi3ZyN');
